
        package com.ca.directory;
        // automatically generated by ant build.xml file.
        //THIS FILE MUST NOT BE ADDED TO CVS OR THE LIVE MAKE SYSTEM

        public class BuildNumber
        {
            public static String value = "JXplorer (build JXv3.2.1rc1 2008-09-05 12:42 EST)";
        }
        